name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Config
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          echo "$(go env GOPATH)/bin/windows_386" >> $GITHUB_PATH

          echo "PORTAPPS_VERSION=$(cat go.mod | grep github.com/portapps/portapps | awk '{print $NF}')" >> $GITHUB_ENV
          echo "PORTAPPS_DIR=./.portapps" >> $GITHUB_ENV

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "GIT_TAGNAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
        shell: bash
      -
        name: Checkout core
        uses: actions/checkout@v2
        with:
          repository: portapps/portapps
          ref: ${{ env.PORTAPPS_VERSION }}
          path: ${{ env.PORTAPPS_DIR }}
      -
        name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Build
        run: |
          ant release -Dcore.dir=${{ env.PORTAPPS_DIR }}
        shell: bash
      -
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: bin/release/*.7z
      -
        name: Transfer to cow
        run: |
          C:\Windows\System32\curl.exe -L https://glare.now.sh/Mikubill/transfer/windows_amd64 -o transfer.zip
          Expand-Archive .\transfer.zip
          .\transfer\transfer.exe cow --block 2621440 -s -p 64 --no-progress (Get-Item bin/release/*.7z).FullName >> cowtransfer.log
          echo "::warning file=cowtransfer.com::$(cat .\cowtransfer.log)"
        shell: powershell
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            bin/release/*.7z
          name: ${{ env.GIT_TAGNAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
